### ISSUE TITLE
Add feature for custom templates

### ISSUE THREAD

**Issue by rnarian** [frdmn/workspace-initiator#5]

**Comment by frdmn** [comment]
What do you mean with "minimal"?

**Comment by rnarian** [comment]
I imagine something without the installation/usage/requirements/contributing blocks. For personal projects or something else that is never published.

**Comment by rnarian** [comment]
Aaahh... Or you could make the blocks optional. 4 extra questions:

```
Add usage block? (y/n)
Add requirements block? (y/n)
(...)
```

**Comment by frdmn** [comment]
Hmm, I think it would be more appropriate to add a readme template for that. Since this is all readme related, a template would be more suitable. I am thinking about custom templates which gets loaded additionally from the homefolder (`~/.init/readmes/*`), so you don't need to send a PR if you want to add your template. I don't really want to add more questions or prompts because it makes the initalization of a new project more time consuming and uncomfortabke. What you think?

**Comment by rnarian** [comment]
Makes total sense. So everything located in `~/.init/readmes/*` will get listed when you run `init`?

**Comment by frdmn** [comment]
exactly... additionally to the global ones in the installation folder (`/usr/local/lib/node_modules/init.js/readmes/`)

**Comment by rnarian** [comment]
:+1:

**Comment by frdmn** [comment]
Added support for custom templates in version [1.2.0](https://github.com/frdmn/init.js/releases/tag/1.2.0).
